name: Unzip Mbatsani

on: [push]

jobs:
    unzip:
          runs-on: ubuntu-latest


          steps:
           - name: Checkpoin repository
             uses: actions/checkout@v2

            - name: Unzip folder
            run: unzip Mbatsani.zip -d .
